### ISSUE TITLE
How can I convert the created header with awot-static to files that can be transfered to a folder on a sdcard?

### ISSUE THREAD

**Issue by ViniDalvino** [lasselukkari/aWOT#121]
My webapp that I created with create-react-app is too big (12 mb)

**Comment by lasselukkari** [comment]
Set the "sdCard" [option](https://github.com/lasselukkari/awot-scripts#example-config) to true and it will generate you a file called static.bin instead of the StaticFiles.h. Copy this file to the SD card and use [CardFiles example](https://github.com/lasselukkari/aWOT/blob/master/examples/CardFiles/CardFiles.ino) to serve your files.

Hope this helps. To be honest 12mb sound like a rather big single page app. How did it get so huge? Feel free to ask more questions if something is not clear.

**Comment by ViniDalvino** [comment]
> To be honest 12mb sound like a rather big single page app
Glad you asked!
My web app is a virtual gamepad for a rc tank. I am going to publish it's source code once I am complete. I hope it's going to showcase well what can aWOT can do :)

**Comment by ViniDalvino** [comment]
here are some screenshots
![settings](https://user-images.githubusercontent.com/37189791/111371992-7c039200-8670-11eb-8766-49551e77c170.png)
![control](https://user-images.githubusercontent.com/37189791/111372051-89b91780-8670-11eb-81ae-7cd780a4d109.png)
![main menu](https://user-images.githubusercontent.com/37189791/111372082-92a9e900-8670-11eb-995d-d083e7c0a713.png)

**Comment by ViniDalvino** [comment]
Can you tell me what you think

**Comment by lasselukkari** [comment]
Sounds nice and look cool! But I still wonder why it takes 12mb. This whole UI fits into ESP32 program memory: http://duinodcx.herokuapp.com/index.html.

**Comment by ViniDalvino** [comment]
It mostly take a lot of space because of the fonts it's using

**Comment by ViniDalvino** [comment]
and because of the images it use since it's also a pwa

**Comment by lasselukkari** [comment]
Ahh ok. That explains it. Can we close the issue?

**Comment by ViniDalvino** [comment]
yes

**Comment by lasselukkari** [comment]
If you can also send me email if you want to discuss your project more.
