### ISSUE TITLE
Using ESPAsyncWebServer for better reliability

### ISSUE THREAD

**Issue by jvoj** [lasselukkari/aWOT#64]
Hi, I really like your lib, good work there! 
Any ideas how to add [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer)? It should act like normal normal WiFiServer but you dont need to wait in loop() for new requests. Other libraries were easily ported onto that, but I am struggling with this one. Thanks!

**Comment by lasselukkari** [comment]
I have no intention to to switch the web server library. I would not even be possible. The [build tooling](https://www.npmjs.com/package/awot-scripts) for building the user interface is heavily dependant on the web server library in use. 

As a author of the [aWOT](https://github.com/lasselukkari/aWOT) library I encourage you to take a look at the documentation available at [awot.net](https://awot.net). There is no reason why it would be any less reliable. The aWOT project actually has some  [tests](https://github.com/lasselukkari/aWOT/tree/master/test).

I recently did a simple benchmark to compare the write performance of three different esp32 web server libraries. As you can see from the [results](https://lasselukkari.github.io/ArduinoServerShootout) in many cases the performance differences are negligible. 

aWOT is cross platform meaning that applications written with it work on any Arduino platform from Uno to ESP32. Also the build tooling for serving static files is far more advanced than anything available for the ESPAsyncWebServer. The memory footprint of the aWOT is minimal compared to the ESPAsyncWebServer.

If you are interested try out the tutorial: https://awot.net/en/guide/tutorial.html

**Comment by lasselukkari** [comment]
I completely misread your comment at first. Here is an updated reply.

In theory this library could use the same async tcp stack as the ESPAsyncWebServer but the conversion is not really possible without really big changes. Also it would at the same time beat the main purpose of this library: being cross platform.

aWOT is cross platform meaning that applications written with it work on any Arduino platform from Uno to ESP32. This is possible because it uses the standard Stream base class instead of any specific web/tcp server implementation. The Stream class is as synchronous as it gets and converting this library to use the same ESPAsyncTCP tcp stack would not make much sense as it would need to be wrapped inside a synchronous api.

I recently did a simple benchmark to compare the write performance of three different esp32 web server libraries. As you can see from the results in many cases the performance differences are negligible. In some cases the synchronous alternative is actually faster.

There is no reason to believe the ESPAsyncWebServer or the ESPAsyncTCP libraries would be any reliable. To be honest there is many reasons to believe the exact opposite.

**Comment by jvoj** [comment]
Thanks for reply. I of course meant implementing server via [ESPAsyncTCP](https://github.com/me-no-dev/ESPAsyncTCP), not via ESPAsyncWebServer which is just alternative to aWOT. My point was that if some part of arduino code uses delay (or some exensive computation) and blocks rest of the loop, aWOT gets stuck also. I see that as anti-pattern for reliable implementations. Implementing it by ESPAsyncTCP would imho solve the problem.

I thought that this can be archieved quite easily, when you take a look into [Server.ino](https://github.com/me-no-dev/ESPAsyncTCP/blob/master/examples/ClientServer/Server/Server.ino) example in ESPAsyncTCP, they are getting new clients via async callback on line 67. Something similar to loop() on your lib. But yea that wouldnt be cross platform, nor even more reliable... And if you say its not worth it, I understand...

**Comment by lasselukkari** [comment]
I would say that it is an antipattern to do anything time consuming inside the http handler. If you need to for example read sensors do it periodically and then just read the stored results in the http handler. If you need to trigger some long lasting operation instead set a flag and do it after http handler has been executed.

**Comment by lasselukkari** [comment]
If you wonder why my initial response was so way off I thought it was for another project. I had two github tabs open at the same time and got mixed up with the repos... Anyway thanks for the positive feedback in your initial message
